// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUy8QmDEGtFMkahk82CA3Mf81V_9posdg',
    appId: '1:1040677308224:web:29b9a6ee084be4f04d5ca5',
    messagingSenderId: '1040677308224',
    projectId: 'masbro-canteen',
    authDomain: 'masbro-canteen.firebaseapp.com',
    storageBucket: 'masbro-canteen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBovZvdTwDG8xbhYTyfc9ffTZui62GrWUc',
    appId: '1:1040677308224:android:eb0444f670c6471c4d5ca5',
    messagingSenderId: '1040677308224',
    projectId: 'masbro-canteen',
    storageBucket: 'masbro-canteen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4CazmFRBDynSj0-LgnP2iM9B17O7Q5TY',
    appId: '1:1040677308224:ios:712cf9b2cafc36e74d5ca5',
    messagingSenderId: '1040677308224',
    projectId: 'masbro-canteen',
    storageBucket: 'masbro-canteen.appspot.com',
    iosBundleId: 'com.example.testgetdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4N-2qSKe_PpzgJONVtkKV4J0ifH9jAfE',
    appId: '1:1062504378190:ios:242e59769174c372d2381f',
    messagingSenderId: '1062504378190',
    projectId: 'mc-notifikasi',
    storageBucket: 'mc-notifikasi.appspot.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHwsV4xegE-xB1GX31EoBBzmzihkmrTo8',
    appId: '1:1062504378190:web:32f4cedeb89e3f2ad2381f',
    messagingSenderId: '1062504378190',
    projectId: 'mc-notifikasi',
    authDomain: 'mc-notifikasi.firebaseapp.com',
    storageBucket: 'mc-notifikasi.appspot.com',
    measurementId: 'G-VTG9S77W39',
  );
}